license connection

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -14,6 +14,15 @@ check_dependencies()
         exit 1
     fi
     
+    make -v >> $LOG_FILE 2>&1
+    if [ $? -ne 0 ]
+    then
+        echo "GNU Make seems to be missing."
+        echo "You need install GNU make"
+        echo
+        exit 1
+    fi
+    
     jq -h >> $LOG_FILE 2>&1
     if [ $? -ne 0 ]
     then
