Tests more structured

diff --git a/Makefile.json b/Makefile.json
--- a/Makefile.json
+++ b/Makefile.json
@@ -25,41 +25,35 @@ JAVA_SOURCES=\
   com/sandklef/compliance/utils/LicenseArbiter.java \
   com/sandklef/compliance/json/JsonLicenseParser.java \
   com/sandklef/compliance/json/JsonPolicyParser.java \
-  com/sandklef/compliance/json/JsonExporter.java \
   com/sandklef/compliance/json/JsonUtils.java \
   com/sandklef/compliance/json/JsonComponentParser.java \
   com/sandklef/compliance/cli/LicenseChecker.java \
-  com/sandklef/compliance/exporter/ReportExporter.java \
-  com/sandklef/compliance/exporter/TestJsonComponentParser.java \
+
 
 TEST_SOURCES=\
-  com/sandklef/compliance/test/TestAll.java\
-  com/sandklef/compliance/test/Utils.java\
-  com/sandklef/compliance/test/TestComponents.java \
-  com/sandklef/compliance/test/TestCanAUseB.java \
-  com/sandklef/compliance/test/TestPolicy.java \
-  com/sandklef/compliance/test/TestDualLicenses.java \
-  com/sandklef/compliance/test/TestMostPermissiveLicenseComparator.java \
-  com/sandklef/compliance/json/test/TestLicenseParser.java \
+  ./com/sandklef/compliance/json/test/TestLicenseParser.java \
+  ./com/sandklef/compliance/json/test/TestJsonComponentParser.java \
+  ./com/sandklef/compliance/test/TestSubComponents.java \
+  ./com/sandklef/compliance/test/TestDualLicenses.java \
+  ./com/sandklef/compliance/test/TestCanAUseB.java \
+  ./com/sandklef/compliance/test/TestComponents.java \
+  ./com/sandklef/compliance/test/TestPrintLicenses.java \
+  ./com/sandklef/compliance/test/TestLicense.java \
+  com/sandklef/compliance/test/TestMostPermissiveLicenseComparator.java
 
 
 CLASSES=$(JAVA_SOURCES:.java=.class)
 TEST_CLASSES=$(TEST_SOURCES:.java=.class)
 
-LIB_DIR=lib
-JSON_JAR=$(LIB_DIR)/org.json.jar
-CLI_JAR=$(LIB_DIR)/commons-cli-1.4.jar
-WINSTONE_JAR=$(LIB_DIR)/winstone.jar
-JUNIT_JAR=$(LIB_DIR)/junit-jupiter-api-5.6.2.jar
-JUNIT_V_JAR=$(LIB_DIR)/junit-vintage-engine-5.6.2.jar
-CLASSPATH=".:$(JSON_JAR):$(CLI_JAR):"
-TEST_CLASSPATH=$(CLASSPATH):$(JUNIT_JAR)
+JSON_JAR=lib/org.json.jar
+CLI_JAR=lib/commons-cli-1.4.jar
+CLASSPATH=".:$(JSON_JAR):$(CLI_JAR)"
 
 %.class:%.java
 	javac  -Xdiags:verbose -cp "$(CLASSPATH)" $<
 
 all: $(CLASSES) $(JSON_JAR) 
-	@echo
+
 
 
 $(CLI_JAR):
@@ -67,23 +61,9 @@ $(CLI_JAR):
 	cd tmp; tar zxvf commons-cli-1.4-bin.tar.gz commons-cli-1.4/commons-cli-1.4.jar
 	cd tmp; mv commons-cli-1.4/commons-cli-1.4.jar ../lib
 
-$(JUNIT_JAR):
-	mkdir -p lib
-	wget "https://search.maven.org/remotecontent?filepath=org/junit/jupiter/junit-jupiter-api/5.6.2/junit-jupiter-api-5.6.2.jar" -O $(JUNIT_JAR)
-
-$(JUNIT_V_JAR):
-	mkdir -p lib
-	wget "https://search.maven.org/remotecontent?filepath=org/junit/vintage/junit-vintage-engine/5.6.2/junit-vintage-engine-5.6.2.jar" -O $(JUNIT_V_JAR)
-
 $(JSON_JAR):
 	mkdir -p lib
-	wget 'https://search.maven.org/remotecontent?filepath=org/json/json/20171018/json-20171018.jar' -O $(LIB_DIR)/org.json.jar
-
-$(WINSTONE_JAR):
-	mkdir -p lib
-	wget 'https://sourceforge.net/projects/winstone/files/latest/download?source=typ_redirect' -O $(LIB_DIR)/winstone.jar
-
-dload-libs: $(JSON_JAR) $(CLI_JAR) $(WINSTONE_JAR) $(JUNIT_JAR) $(JUNIT_V_JAR)
+	wget 'https://search.maven.org/remotecontent?filepath=org/json/json/20171018/json-20171018.jar' -O lib/org.json.jar
 
 $(CLASSES): $(JSON_JAR) $(CLI_JAR)
 
@@ -104,15 +84,30 @@ stat:
 	@echo "Json: " ; 
 	@echo -n " * files: " ; find . -name "*.json" | wc -l
 	@echo -n " * loc: " ; find . -name "*.json" | xargs wc -l| tail -1
-	@echo "Bash: " ; 
-	@echo -n " * files: " ; find . -name "*.sh" -o -name configure | wc -l
-	@echo -n " * loc: " ; find . -name "*.sh"  -o -name configure | xargs wc -l| tail -1
 
 clean:
 	rm -f $(CLASSES)
 	find -name "*~" | xargs rm -f
 	find -name "*.class" | xargs rm -f
 
-test: $(JUNIT_JAR) all $(TEST_CLASSES) 
-	java -ea -cp $(CLASSPATH) com/sandklef/compliance/test/TestAll
+test: test-all test-json 
 
+test-all: $(TEST_CLASSES)
+	for i in $(TEST_CLASSES); \
+	do \
+		export CLASS=`echo $$i | sed -e 's,\.class,,g' -e 's,/,\.,g'` ; \
+		echo "Test: $$CLASS"; \
+		java -ea -cp $(CLASSPATH) $$CLASS ; \
+		if [ $$? -ne 0 ] ; then echo "$$CLASS failed"; break; fi ; \
+	done;
+
+test-comparator:com/sandklef/compliance/test/TestMostPermissiveLicenseComparator.class $(CLASSES) $(JSON_JAR)
+	java -cp $(CLASSPATH) com/sandklef/compliance/test/TestMostPermissiveLicenseComparator
+
+test-json: ./com/sandklef/compliance/json/test/TestJsonParser.class  com/sandklef/compliance/json/test/TestLicenseParser.class $(CLASSES) $(JSON_JAR)
+	@echo " --- License parsers ----"
+	java -cp $(CLASSPATH) com.sandklef.compliance.json.test.TestLicenseParser --verbose ./licenses/json/
+	@echo " --- Json parsers ----"
+	java -cp $(CLASSPATH) com.sandklef.compliance.json.test.TestJsonParser --verbose ./com/sandklef/compliance/json/test/simple.json
+	@echo " --- Json parsers with violation expected ----"
+	java -cp $(CLASSPATH) com.sandklef.compliance.json.test.TestJsonParser --violation --verbose ./com/sandklef/compliance/json/test/simple-problem.json
